### ISSUE TITLE
 Error: authMode: must be of type String

### ISSUE THREAD

**Issue by thebetterjort** [httpsOmkar/keycloak-hasura-connector#33]
Error from images:

```
auth_1            | > node src/main.js
auth_1            | 
auth_1            | /usr/src/app/node_modules/convict/lib/convict.js:686
auth_1            |           throw new Error(output);
auth_1            |           ^
auth_1            | 
auth_1            | Error: authMode: must be of type String

```

```
version: '3.6'
services:


  postgres:
    image: postgres
    restart: always
    volumes:
      - ./data:/data
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      
  auth:
    image: httpsomkar/keycloak-hasura-connector:latest
    environment:
      KEYCLOAK_CLIENT_ID: hasura
      KEYCLOAK_SERVER_URL: https://localhost
      KEYCLOAK_REALM: master
      KEYCLOAK_SECRET: dsfsdafsdfasdfasdfasd
      ANONYMOUS_ROLE: "anonymous" # (optional) Use this variable to set anonymous role name for unauthorized users as shown in the documentation: https://docs.hasura.io/1.0/graphql/manual/auth/authorization/common-roles-auth-examples.html#anonymous-not-logged-in-users
      USER_ID_FIELD: "sub" #The name of the token field that will be mapped to X-Hasura-User-Id
      KEYCLOAK_DEBUG: "true" # If testing enable mention this file

  graphql-engine:
    image: hasura/graphql-engine:latest
    ports:
      - "9090:8080"
    depends_on:
      - "postgres"
      - "auth"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey # Your admin secret
      HASURA_GRAPHQL_AUTH_HOOK: http://auth:3000

volumes:
  db_data:

```
