### ISSUE TITLE
Error: AnonymousRole: must be of type String

### ISSUE THREAD

**Issue by Ticunas** [httpsOmkar/keycloak-hasura-connector#34]
I'm getting error from image  
  
Stack Trace:
```
auth_1            | 
auth_1            | > hasura-connector@0.0.1-beta start /usr/src/app
auth_1            | > node src/main.js
auth_1            | 
auth_1            | /usr/src/app/node_modules/convict/lib/convict.js:686
auth_1            |           throw new Error(output);
auth_1            |           ^
auth_1            | 
auth_1            | Error: AnonymousRole: must be of type String
auth_1            |     at Object.validate (/usr/src/app/node_modules/convict/lib/convict.js:686:17)
auth_1            |     at Object.<anonymous> (/usr/src/app/src/config.js:80:8)
auth_1            |     at Module._compile (internal/modules/cjs/loader.js:936:30)
auth_1            |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
auth_1            |     at Module.load (internal/modules/cjs/loader.js:790:32)
auth_1            |     at Function.Module._load (internal/modules/cjs/loader.js:703:12)
auth_1            |     at Module.require (internal/modules/cjs/loader.js:830:19)
auth_1            |     at require (internal/modules/cjs/helpers.js:68:18)
auth_1            |     at Object.<anonymous> (/usr/src/app/src/main.js:3:16)
auth_1            |     at Module._compile (internal/modules/cjs/loader.js:936:30)
auth_1            | npm ERR! code ELIFECYCLE
auth_1            | npm ERR! errno 1
auth_1            | npm ERR! hasura-connector@0.0.1-beta start: `node src/main.js`
auth_1            | npm ERR! Exit status 1
auth_1            | npm ERR! 
auth_1            | npm ERR! Failed at the hasura-connector@0.0.1-beta start script.
auth_1            | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
auth_1            | 
auth_1            | npm ERR! A complete log of this run can be found in:
auth_1            | npm ERR!     /root/.npm/_logs/2019-12-04T20_22_20_529Z-debug.log
```
.env  
```
KEYCLOAK_USERNAME=keycloak
KEYCLOAK_PASSWORD=keycloak
AUTH_MODE=single
KEYCLOAK_URL=http://localhost:8080/auth/
KEYCLOAK_REALM=hasura
KEYCLOAK_CLIENT_ID=Keycloak-hasura-connector
KEYCLOAK_SECRET=7741f5c8-dd5b-4bae-a838-e970c6ecc005
```
docker-compose.yml  
```
version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak

    volumes:
      - auth_db_keycloak_connector:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USERNAME}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_USER: keycloak
      DB_PASSWORD: keycloak

  auth:
    image: httpsomkar/keycloak-hasura-connector:latest
    depends_on:
      - "keycloak"
    environment:
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_SERVER_URL: ${KEYCLOAK_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_SECRET: ${KEYCLOAK_SECRET}
      KEYCLOAK_DEBUG: "true"

  postgres_db:
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data

  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-alpha42
    ports:
      - "8081:8080"
    depends_on:
      - "postgres_db"
      - "auth"
      - "keycloak"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres_db:5432/postgres
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false" # https://docs.hasura.io/1.0/graphql/manual/guides/telemetry.html
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ADMIN_SECRET: admin
      HASURA_GRAPHQL_AUTH_HOOK: http://auth:3000

volumes:
  db_data:
  auth_db_keycloak_connector:
```

**Comment by httpsOmkar** [comment]
```
KEYCLOAK_USERNAME=keycloak
KEYCLOAK_PASSWORD=keycloak
AUTH_MODE=single
KEYCLOAK_URL=http://localhost:8080/auth/
KEYCLOAK_REALM=hasura
KEYCLOAK_CLIENT_ID=Keycloak-hasura-connector
KEYCLOAK_SECRET=7741f5c8-dd5b-4bae-a838-e970c6ecc005
ANONYMOUS_ROLE=guest
```
try this as .env

**Comment by Ticunas** [comment]
I used exactly the same .env of your comment, but issue persist with same stack trace

**Comment by httpsOmkar** [comment]
Ohh I got that

```yaml
version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak

    volumes:
      - auth_db_keycloak_connector:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USERNAME}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_USER: keycloak
      DB_PASSWORD: keycloak

  auth:
    image: httpsomkar/keycloak-hasura-connector:latest
    depends_on:
      - "keycloak"
    environment:
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_SERVER_URL: ${KEYCLOAK_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_SECRET: ${KEYCLOAK_SECRET}
      KEYCLOAK_DEBUG: "true"
      ANONYMOUS_ROLE: "guest"

  postgres_db:
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data

  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-alpha42
    ports:
      - "8081:8080"
    depends_on:
      - "postgres_db"
      - "auth"
      - "keycloak"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres_db:5432/postgres
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false" # https://docs.hasura.io/1.0/graphql/manual/guides/telemetry.html
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ADMIN_SECRET: admin
      HASURA_GRAPHQL_AUTH_HOOK: http://auth:3000

volumes:
  db_data:
  auth_db_keycloak_connector:
```
My bad try this as docker-compose file
